--------------------------------------------------------
--  DDL for Table USER_LOGIN
--------------------------------------------------------

  CREATE TABLE "JPY"."USER_LOGIN" 
   (	"USERID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"MOBILE" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"LASTACCESSED" DATE, 
	"FAILEDCOUNT" NUMBER(*,0), 
	"EXPIREDATE" DATE, 
	"STATUS" CHAR(1 BYTE)
   ) 
  TABLESPACE "LOB_01" ;
  
  
--------------------------------------------------------
--  DDL for Table USER_INFO
--------------------------------------------------------

  CREATE TABLE "JPY"."USER_INFO" 
   (	"USERID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"FIRSTNAME" VARCHAR2(50 BYTE), 
	"LASTNAME" VARCHAR2(50 BYTE), 
	"GENDER" CHAR(1 BYTE), 
	"DATEOFBIRTH" DATE, 
	"DEPARTMENT" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"SCHEMAID" VARCHAR2(50 BYTE), 
	"EEGROUPID" VARCHAR2(50 BYTE)
   ) 
  TABLESPACE "LOB_01" ;

--------------------------------------------------------
--  DDL for Sequence USER_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "JPY"."USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

   
   --------------------------------------------------------
--  DDL for Table CONF_SCHEMA
--------------------------------------------------------

  CREATE TABLE "JPY"."CONF_SCHEMA" 
   (	"SCHEMAID" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"SCHEMACONTENT" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01" 
 LOB ("SCHEMACONTENT") STORE AS BASICFILE (
  TABLESPACE "LOB_01" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index CONF_SCHEMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JPY"."CONF_SCHEMA_PK" ON "JPY"."CONF_SCHEMA" ("SCHEMAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01" ;
--------------------------------------------------------
--  Constraints for Table CONF_SCHEMA
--------------------------------------------------------

  ALTER TABLE "JPY"."CONF_SCHEMA" ADD CONSTRAINT "CONF_SCHEMA_PK" PRIMARY KEY ("SCHEMAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01"  ENABLE;
 
  ALTER TABLE "JPY"."CONF_SCHEMA" MODIFY ("SCHEMAID" NOT NULL ENABLE);

  
  --------------------------------------------------------
--  DDL for Table CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "JPY"."CONFIGURATION" 
   (	"CONFIG_TYPE" VARCHAR2(50 BYTE), 
	"EEGROUPID" VARCHAR2(50 BYTE), 
	"MIN" NUMBER(10,0), 
	"MAX" NUMBER(10,0), 
	"AMOUNT1" NUMBER(15,2), 
	"AMOUNT2" NUMBER(15,2), 
	"AMOUNT3" NUMBER(15,2), 
	"AMOUNT4" NUMBER(15,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01" ;
--------------------------------------------------------
--  DDL for Index CONFIGURATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JPY"."CONFIGURATION_PK" ON "JPY"."CONFIGURATION" ("CONFIG_TYPE", "EEGROUPID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01" ;
--------------------------------------------------------
--  Constraints for Table CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "JPY"."CONFIGURATION" ADD CONSTRAINT "CONFIGURATION_PK" PRIMARY KEY ("CONFIG_TYPE", "EEGROUPID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01"  ENABLE;
 
  ALTER TABLE "JPY"."CONFIGURATION" MODIFY ("CONFIG_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "JPY"."CONFIGURATION" MODIFY ("EEGROUPID" NOT NULL ENABLE);
  
  
  
  --------------------------------------------------------
--  DDL for Table WAGE_TYPE
--------------------------------------------------------

  CREATE TABLE "JPY"."WAGE_TYPE" 
   (	"WAGETYPEID" VARCHAR2(20 BYTE), 
	"SEQUENCE" NUMBER(*,0) DEFAULT 0, 
	"BEGDA" DATE, 
	"ENDDA" DATE, 
	"AMOUNT" NUMBER(15,2), 
	"COUNT" NUMBER(10,0) DEFAULT 1, 
	"CURRENCY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01" ;
--------------------------------------------------------
--  DDL for Index WAGE_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JPY"."WAGE_TYPE_PK" ON "JPY"."WAGE_TYPE" ("WAGETYPEID", "SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01" ;
--------------------------------------------------------
--  Constraints for Table WAGE_TYPE
--------------------------------------------------------

  ALTER TABLE "JPY"."WAGE_TYPE" MODIFY ("WAGETYPEID" NOT NULL ENABLE);
 
  ALTER TABLE "JPY"."WAGE_TYPE" MODIFY ("SEQUENCE" NOT NULL ENABLE);
 
  ALTER TABLE "JPY"."WAGE_TYPE" ADD CONSTRAINT "WAGE_TYPE_PK" PRIMARY KEY ("WAGETYPEID", "SEQUENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "LOB_01"  ENABLE;
